version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ubuntuconnectdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: ubuntu_connect_container
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_URL: jdbc:mysql://mysql:3306/ubuntuconnectdb
    ports:
      - "8080:8080"
    depends_on:
      - mysql
